
import "./globals.css";
import { Lato } from 'next/font/google';

const lato = Lato({
  weight: ["400","100","300","700"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata = {
  title: "Messaging App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
